// Development-only: render the catalog banner and gallery.
//
// The look joins the two projects this plugin connects. Honcho supplies the
// frame: a charcoal canvas with a faint grid, window chrome with double rules
// and bracketed titles, pixel-block clusters, right-angle connectors and a CLI
// box. Nous supplies the content: a Nous-blue strip, original generated art
// (the Nous girl and esoteric geometry) dithered into Nous blue, Neuebit
// headlines, Mondwest mottos and four-point sparkles. The UI is the plugin's
// dark theme with synthetic data.
//
// Art is generated by Hermes's bundled `openai-codex` image provider
// (gpt-image-2). The character prompts used the MIT-licensed Nous Girl mark
// from hermes-agent as a reference image. Prompts, provenance and the MIT
// notice are in docs/catalog/art. Every image says it is an unofficial
// community plugin, and nothing implies affiliation with Nous Research or
// Plastic Labs. Fonts load from the prepared Hermes checkout's
// @nous-research/ui package (MIT) at render time and are not copied.
//
//   HERMES_SOURCE=/path/to/hermes-agent node scripts/catalog-art.mjs
//
// Optional: CATALOG_ART_OUTPUT (default docs/catalog), CATALOG_ART_SOURCES
// (default docs/catalog/art), CATALOG_ART_ONLY=banner.png,gallery-ask.png
import assert from 'node:assert/strict'
import { createServer } from 'node:http'
import { createRequire } from 'node:module'
import { mkdir, readdir, readFile } from 'node:fs/promises'
import { dirname, extname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = resolve(dirname(fileURLToPath(import.meta.url)), '..')
assert(process.env.HERMES_SOURCE, 'Set HERMES_SOURCE to a prepared Hermes checkout.')
const host = resolve(process.env.HERMES_SOURCE)
const { chromium } = createRequire(join(host, 'package.json'))('playwright')
const fonts = join(host, 'node_modules/@nous-research/ui/dist/fonts')
const assets = join(host, 'apps/desktop/dist/assets')
const shots = join(repo, 'docs/screenshots')
const sources = resolve(process.env.CATALOG_ART_SOURCES || join(repo, 'docs/catalog/art'))
const output = resolve(process.env.CATALOG_ART_OUTPUT || join(repo, 'docs/catalog'))
const only = process.env.CATALOG_ART_ONLY ? new Set(process.env.CATALOG_ART_ONLY.split(',')) : null
await mkdir(output, { recursive: true })
const mono = (await readdir(assets)).find(name => /^JetBrainsMono-Regular-.*\.woff2$/.test(name))
assert(mono, 'Build Hermes Desktop first: JetBrains Mono not found in apps/desktop/dist/assets.')
const sourceFiles = Object.fromEntries((await readdir(sources)).filter(name => /\.(jpe?g|png)$/i.test(name)).map(name => [name.replace(/\.[^.]+$/, ''), name]))

// Nous
const BLUE = '#0000f2'
const PAPER = '#f2f2f2'
const PALE = '#8a8aff'
// Honcho
const CHARCOAL = '#1a1a1a'
const INK = '#e3e3e3'
const MUTED = '#8f8f8f'
const RULE = '#6b6b6b'
const SKY = '#b8d4f2'
const MINT = '#a8f0d8'
const BLOCK = '#2b3440'
// The screenshot harness adds a 38px "synthetic demo data" bar to every capture.
const BAR = 38

// ── Ornaments ───────────────────────────────────────────────────────────────

// An original memory sigil: a heptagram with every chord, tick rings and nodes.
function sigil(size, { ink = INK, field = CHARCOAL, points = 7, ticks = true, weight = 1 } = {}) {
  const c = size / 2
  const outer = c - weight
  const ring = outer * 0.72
  const node = Math.max(2.5, outer * 0.07)
  const f = n => n.toFixed(2)
  const angle = i => -Math.PI / 2 + (i * 2 * Math.PI) / points
  const at = (r, i) => [c + r * Math.cos(angle(i)), c + r * Math.sin(angle(i))]
  const chords = []
  for (let i = 0; i < points; i++) {
    for (let j = i + 1; j < points; j++) {
      const [x1, y1] = at(ring, i)
      const [x2, y2] = at(ring, j)
      chords.push(`<line x1="${f(x1)}" y1="${f(y1)}" x2="${f(x2)}" y2="${f(y2)}"/>`)
    }
  }
  const tickMarks = ticks
    ? Array.from({ length: 72 }, (_, i) => {
        const a = (i * Math.PI * 2) / 72
        const inner = outer * (i % 6 === 0 ? 0.86 : 0.92)
        return `<line x1="${f(c + inner * Math.cos(a))}" y1="${f(c + inner * Math.sin(a))}" x2="${f(c + outer * 0.97 * Math.cos(a))}" y2="${f(c + outer * 0.97 * Math.sin(a))}"/>`
      }).join('')
    : ''
  const nodes = Array.from({ length: points }, (_, i) => {
    const [x, y] = at(ring, i)
    return `<circle cx="${f(x)}" cy="${f(y)}" r="${f(node)}"/>`
  }).join('')
  return `<svg viewBox="0 0 ${size} ${size}" width="${size}" height="${size}" style="display:block;overflow:visible">
    <g fill="none" stroke="${ink}" stroke-width="${weight}">
      <circle cx="${c}" cy="${c}" r="${f(outer)}"/>${ticks ? `<circle cx="${c}" cy="${c}" r="${f(outer * 0.84)}"/>` : ''}
      <g stroke-width="${weight * 0.7}" opacity="0.85">${chords.join('')}${tickMarks}</g>
    </g>
    <g fill="${field}" stroke="${ink}" stroke-width="${weight}">${nodes}<circle cx="${c}" cy="${c}" r="${f(node * 1.3)}"/></g>
  </svg>`
}

function spark(x, y, size, color = PAPER) {
  return `<svg class="spark" viewBox="-10 -10 20 20" style="left:${x - size / 2}px;top:${y - size / 2}px;width:${size}px;height:${size}px"><path fill="${color}" d="M0,-10 C0.9,-0.9 0.9,-0.9 10,0 C0.9,0.9 0.9,0.9 0,10 C-0.9,0.9 -0.9,0.9 -10,0 C-0.9,-0.9 -0.9,-0.9 0,-10Z"/></svg>`
}

// Honcho's pixel-block clusters. `cells` are [col, row] on a 25px grid.
function blocks(x, y, cells, color = BLOCK, size = 18) {
  return cells.map(([cx, cy]) => `<div class="block" style="left:${x + cx * 25}px;top:${y + cy * 25}px;width:${size}px;height:${size}px;background:${color}"></div>`).join('')
}

// A right-angle connector: points are [x, y] in page coordinates.
function connector(points, color = RULE) {
  return `<svg class="wire" width="1200" height="600"><polyline fill="none" stroke="${color}" stroke-width="1" points="${points.map(p => p.join(',')).join(' ')}"/></svg>`
}

// A Honcho window: double rules either side of a bracketed title, then a close mark.
function win({ x, y, w, h, title, body, z = 3 }) {
  return `<div class="win" style="left:${x}px;top:${y}px;width:${w}px;height:${h}px;z-index:${z}">
    <div class="bar"><span class="rules"></span><span class="title">[${title}]</span><span class="rules"></span><span class="close">×</span></div>
    <div class="body">${body}</div>
  </div>`
}

// Generated ink art, dithered into Nous blue on paper: ink becomes blue, mid
// tones pale-blue dots. `focus` (a point in the source) lands at `at` in the
// canvas; `zoom` is the share of the source width shown across it. `glitch`
// adds that many corrupted scanlines.
function art({ key, focus = [0.5, 0.5], at = [0.5, 0.5], zoom = 1, gamma = 1, cell = 2, glitch = 0 }) {
  assert(sourceFiles[key], `Missing generated art: ${key}`)
  return `<canvas data-art="/src/${encodeURIComponent(sourceFiles[key])}" data-focus="${focus}" data-at="${at}" data-zoom="${zoom}" data-gamma="${gamma}" data-cell="${cell}" data-glitch="${glitch}"></canvas>`
}

// A screenshot region: source CSS pixels [x, y, width] from a capture that is
// `source` CSS pixels wide, scaled to fill the window body.
function shot({ file, crop = [0, 0, 1200], source = 1200, width }) {
  const [x, y, w] = crop
  const scale = width / w
  return `<img class="shot" src="/shots/${file}" style="width:${source * scale}px;margin-left:${-x * scale}px;margin-top:${-(BAR + y) * scale}px">`
}

function strip(left, right = 'SYNTHETIC DEMO DATA') {
  return `<div class="strip"><span>${left}</span><span>UNOFFICIAL COMMUNITY PLUGIN</span><span>${right}</span></div>`
}

const foot = `<div class="foot">${sigil(40, { ink: SKY, ticks: false })}<div><div class="pixel">HONCHO MEMORY</div><div class="pixel dim">FOR HERMES AGENT</div></div></div>`

// ── Gallery plates ──────────────────────────────────────────────────────────

const ART = { x: 436, y: 62, w: 372, h: 498 }
const UI = { x: 712, y: 196, w: 456, h: 330 }

function plate({ number, section, headline, motto, body, artwork, figure, ui, extra = '', box = ART }) {
  const panes = Array.isArray(ui) ? ui : null
  const ART = box
  return `<div class="grid"></div>${strip(`PL. ${number} · ${section.toUpperCase()}`)}
  <div class="col">
    <div class="pixel sky">${section.toUpperCase()}</div>
    <div class="headline" data-fit="352">${headline.join('<br>')}</div>
    <div class="motto">${motto}</div>
    <p class="body">${body}</p>
    <div style="flex:1"></div>
    ${foot}
  </div>
  ${win({ ...ART, title: `FIG. ${number} · ${figure}`, body: art(artwork) })}
  ${panes
    ? panes.map((pane, i) => win({ x: ART.x + ART.w + 22 + i * 196, y: 80 + i * 30, w: 184, h: 470, title: pane.title, z: 4 + i, body: shot({ ...pane, source: 380, width: 182 }) })).join('')
    : win({ ...UI, title: ui.title, z: 4, body: shot({ ...ui, width: UI.w - 2 }) })}
  ${connector([[ART.x + ART.w / 2, ART.y + ART.h], [ART.x + ART.w / 2, 584], [1040, 584], [1040, panes ? 586 : UI.y + UI.h]])}
  ${blocks(1072, 52, [[0, 0], [1, 0], [1, 1], [2, 1], [3, 1], [2, 2]])}
  ${blocks(400, 520, [[0, 0], [0, 1], [1, 1]], BLUE)}
  ${extra}`
}

const PLATES = {
  'gallery-memory.png': {
    number: 'I', section: 'Memory', headline: ['See what it', 'concluded'], motto: 'Quod scitur, manet.',
    body: 'Newest conclusions from the chat’s Honcho session. Open one to see its premises and what was derived from it.',
    figure: 'ORBIS MEMORIAE', artwork: { key: 'memory', focus: [0.5, 0.42], at: [0.5, 0.42], zoom: 1 },
    ui: { title: 'MEMORY', file: 'provenance.png', crop: [40, 18, 1120] },
    extra: spark(842, 132, 16) + spark(1150, 560, 10)
  },
  'gallery-ask.png': {
    number: 'II', section: 'Ask', headline: ['Ask your', 'memory'], motto: 'Interroga memoriam.',
    body: 'Runs only when you ask. Lists the records Honcho read, so you can check the answer yourself.',
    figure: 'ORACULUM', artwork: { key: 'ask', focus: [0.5, 0.45], at: [0.5, 0.45], zoom: 1 },
    ui: { title: 'ASK', file: 'ask-memory.png', crop: [40, 18, 900] },
    extra: spark(846, 138, 16) + spark(1150, 560, 10)
  },
  'gallery-correct.png': {
    number: 'III', section: 'Correct', headline: ['Fix what it', 'got wrong'], motto: 'Corrige, non dele.',
    body: 'Adds one explicit fact to the session you confirmed. Nothing is deleted, and the saved text is read back.',
    figure: 'TABULAE', artwork: { key: 'correct', focus: [0.5, 0.45], at: [0.5, 0.45], zoom: 1 },
    ui: { title: 'ADD A FACT', file: 'correction.png', crop: [296, 150, 608] },
    extra: spark(846, 138, 16) + spark(1150, 560, 10)
  },
  'gallery-pane.png': {
    number: 'IV', section: 'Side pane', headline: ['Stays with', 'your chat'], motto: 'Semper ad latus.',
    body: 'Docks beside the conversation and follows the chat in focus, including chats from your other profiles.',
    figure: 'FENESTRA', artwork: { key: 'pane', focus: [0.6, 0.5], at: [0.5, 0.5], zoom: 0.68 }, box: { x: 436, y: 62, w: 324, h: 498 },
    ui: [
      { title: 'PANE', file: 'memory-pane.png', crop: [0, 0, 380] },
      { title: 'INSPECTOR', file: 'memory-pane-detail.png', crop: [0, 0, 380] }
    ]
  },
  'gallery-messages.png': {
    number: 'V', section: 'Messages', headline: ['Search what', 'was said'], motto: 'Verba volant, scripta manent.',
    body: 'Saved messages for the session, plus Honcho search across the session, the user, or the whole workspace.',
    figure: 'NUNTII', artwork: { key: 'messages', focus: [0.5, 0.45], at: [0.5, 0.45], zoom: 1 },
    ui: { title: 'MESSAGES', file: 'search.png', crop: [40, 18, 900] },
    extra: spark(846, 138, 16) + spark(1150, 560, 10)
  },
  'gallery-status.png': {
    number: 'VI', section: 'Status', headline: ['Know where', 'it lives'], motto: 'Ubi memoria habitat.',
    body: 'Connection, profile, Honcho session, and background reasoning for the chat in view.',
    figure: 'SPHAERA', artwork: { key: 'status', focus: [0.5, 0.42], at: [0.5, 0.42], zoom: 1 },
    ui: { title: 'STATUS', file: 'diagnostics.png', crop: [40, 18, 1120] },
    extra: spark(846, 138, 16) + spark(1150, 560, 10)
  }
}

// ── Banners ─────────────────────────────────────────────────────────────────

const MOTTO = 'Memoria quae ratiocinatur.'
const CLI = `<div class="cli"><span class="cli-k">HERMES CLI</span><span class="cli-p">you@hermes ~ %</span><span>hermes plugins install hermes-honcho-plugin</span><span class="cursor"></span></div>`
const HERO = { key: 'hero', focus: [0.56, 0.44], at: [0.5, 0.44], zoom: 0.96, glitch: 7 }

const BANNERS = {
  'banner.png': `<div class="grid"></div>${strip('PL. 0', 'NOT AFFILIATED WITH NOUS RESEARCH OR PLASTIC LABS')}
    <div class="col" style="width:560px">
      <div class="pixel sky">HERMES AGENT · DESKTOP PLUGIN</div>
      <div class="headline" data-fit="560" style="font-size:150px">Honcho<br>Memory</div>
      <div class="motto" style="font-size:21px">${MOTTO}</div>
      <p class="body" style="max-width:500px;font-size:13.5px">Read, search, question, and correct the Honcho memory behind the chat in front of you.</p>
      <div style="flex:1"></div>
      ${CLI}
    </div>
    ${win({ x: 642, y: 56, w: 520, h: 508, title: 'FIG. 0 · MEMORIA', body: art(HERO) })}
    ${blocks(588, 92, [[0, 0], [0, 1], [1, 1], [1, 2]])}
    ${blocks(560, 466, [[1, 0], [0, 1], [1, 1], [2, 1]], BLUE)}
    ${blocks(1120, 568, [[0, 0], [1, 0]])}
    ${connector([[1040, 564], [1040, 586], [560, 586], [560, 548]])}
    ${spark(612, 180, 18)}${spark(1178, 300, 10)}`
}

const pages = {
  ...BANNERS,
  ...Object.fromEntries(Object.entries(PLATES).map(([name, data]) => [name, plate(data)]))
}

// ── Page ────────────────────────────────────────────────────────────────────

const css = `
@font-face { font-family: Mondwest; src: url(/fonts/Mondwest-Regular.woff2) format('woff2'); }
@font-face { font-family: Neuebit; src: url(/fonts/Neuebit-Bold.woff2) format('woff2'); }
@font-face { font-family: Mono; src: url(/assets/${mono}) format('woff2'); }
* { box-sizing: border-box; margin: 0; padding: 0; }
html, body { width: 1200px; height: 600px; overflow: hidden; background: ${CHARCOAL}; color: ${INK}; }
body { position: relative; font-family: Mono, monospace; -webkit-font-smoothing: antialiased; }
.grid { position: absolute; inset: 0; background-color: ${CHARCOAL};
  background-image: linear-gradient(rgba(255,255,255,0.045) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.045) 1px, transparent 1px);
  background-size: 25px 25px; background-position: -1px -1px; }
.strip { position: absolute; left: 0; right: 0; top: 0; height: 30px; background: ${BLUE}; color: ${PAPER}; z-index: 10;
  display: flex; justify-content: space-between; align-items: center; padding: 0 20px; font: 16px/1 Neuebit; letter-spacing: 0.12em; }
.col { position: absolute; left: 44px; top: 62px; bottom: 34px; width: 360px; display: flex; flex-direction: column; z-index: 5; }
.pixel { font: 16px/1 Neuebit; letter-spacing: 0.14em; text-transform: uppercase; }
.sky { color: ${SKY}; }
.dim { color: ${MUTED}; margin-top: 4px; }
.headline { font: 92px/0.86 Neuebit; text-transform: uppercase; letter-spacing: 0.01em; margin-top: 18px; width: max-content; white-space: nowrap; color: ${INK}; }
.motto { font: 18px/1.2 Mondwest; margin-top: 16px; color: ${SKY}; }
.body { font: 12.5px/1.65 Mono; margin-top: 12px; max-width: 340px; color: rgba(227,227,227,0.82); }
.foot { display: flex; gap: 12px; align-items: center; margin-top: 16px; }
.win { position: absolute; background: ${CHARCOAL}; border: 1px solid ${RULE}; display: flex; flex-direction: column; box-shadow: 0 0 0 6px rgba(26,26,26,0.9); }
.bar { height: 34px; flex: none; display: flex; align-items: center; gap: 12px; padding: 0 12px 0 14px; border-bottom: 1px solid ${RULE}; }
.rules { flex: 1; height: 5px; border-top: 1px solid ${MUTED}; border-bottom: 1px solid ${MUTED}; }
.title { font: 16px/1 Neuebit; letter-spacing: 0.12em; color: ${INK}; white-space: nowrap; }
.close { font: 15px/1 Mono; color: ${INK}; margin-left: 6px; }
.body { position: relative; }
.win > .body { flex: 1; overflow: hidden; margin: 0; max-width: none; position: relative; }
.win > .body canvas { position: absolute; inset: 0; width: 100%; height: 100%; image-rendering: pixelated; }
.shot { display: block; }
.block { position: absolute; z-index: 2; }
.wire { position: absolute; left: 0; top: 0; z-index: 1; }
.spark { position: absolute; z-index: 8; }
.cli { display: flex; align-items: center; gap: 14px; height: 38px; padding: 0 16px; background: #111; border: 1px solid #333;
  font: 12px/1 Mono; color: ${INK}; white-space: nowrap; box-shadow: 0 6px 24px rgba(0,0,0,0.45); }
.cli-k { font: 16px/1 Neuebit; letter-spacing: 0.12em; }
.cli-p { color: ${MUTED}; }
.cursor { width: 8px; height: 15px; background: ${INK}; margin-left: -8px; }
`

// Ordered (Bayer 8x8) dither of black-on-white ink art into Nous blue on paper.
const pageScript = `
const BAYER = [0,32,8,40,2,34,10,42,48,16,56,24,50,18,58,26,12,44,4,36,14,46,6,38,60,28,52,20,62,30,54,22,3,35,11,43,1,33,9,41,51,19,59,27,49,17,57,25,15,47,7,39,13,45,5,37,63,31,55,23,61,29,53,21]
window.render = async () => {
  for (const el of document.querySelectorAll('[data-fit]')) {
    let size = parseFloat(getComputedStyle(el).fontSize)
    while (el.offsetWidth > Number(el.dataset.fit) && size > 24) { size -= 1; el.style.fontSize = size + 'px' }
  }
  for (const canvas of document.querySelectorAll('canvas[data-art]')) {
    const d = canvas.dataset
    const image = new Image(); image.src = d.art; await image.decode()
    const W = canvas.width = Math.round(canvas.clientWidth * 2)
    const H = canvas.height = Math.round(canvas.clientHeight * 2)
    const cell = Number(d.cell)
    const gw = Math.ceil(W / cell), gh = Math.ceil(H / cell)
    const [fx, fy] = d.focus.split(',').map(Number), [tx, ty] = d.at.split(',').map(Number)
    const sw = Number(d.zoom) * image.width, sh = sw * gh / gw
    const clamp = (start, span, total) => span >= total ? (total - span) / 2 : Math.min(Math.max(start, 0), total - span)
    const sx = clamp(fx * image.width - tx * sw, sw, image.width)
    const sy = clamp(fy * image.height - ty * sh, sh, image.height)
    const work = document.createElement('canvas'); work.width = gw; work.height = gh
    const ctx = work.getContext('2d', { willReadFrequently: true })
    ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, gw, gh)
    ctx.drawImage(image, sx, sy, sw, sh, 0, 0, gw, gh)
    const px = ctx.getImageData(0, 0, gw, gh).data
    const out = canvas.getContext('2d')
    out.fillStyle = '${PAPER}'; out.fillRect(0, 0, W, H)
    for (let y = 0; y < gh; y++) for (let x = 0; x < gw; x++) {
      const i = (y * gw + x) * 4
      const ink = (1 - (0.2126 * px[i] + 0.7152 * px[i + 1] + 0.0722 * px[i + 2]) / 255) ** Number(d.gamma)
      const t = (BAYER[(y % 8) * 8 + (x % 8)] + 0.5) / 64
      if (ink > 0.5) out.fillStyle = '${BLUE}'
      else if (ink > 0.12 + 0.34 * t) out.fillStyle = '${PALE}'
      else continue
      out.fillRect(x * cell, y * cell, cell, cell)
    }
    // Honcho-style corrupted scanlines: deterministic horizontal slices.
    let seed = 7
    const rand = () => ((seed = (seed * 16807) % 2147483647) / 2147483647)
    for (let k = 0; k < Number(d.glitch); k++) {
      const y0 = Math.floor(rand() * H), h = 4 + Math.floor(rand() * 26), dx = Math.floor((rand() - 0.5) * 60)
      out.drawImage(canvas, 0, y0, W, h, dx, y0, W, h)
      out.fillStyle = k % 2 ? '${MINT}59' : '${SKY}59'
      out.fillRect(0, y0 + Math.floor(h / 2), W, 2)
    }
  }
}
`

const mime = { '.woff2': 'font/woff2', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.html': 'text/html' }
const server = createServer(async (request, response) => {
  try {
    const path = decodeURIComponent(new URL(request.url, 'http://art').pathname)
    if (path.includes('..')) throw new Error('bad path')
    let file
    if (path.startsWith('/fonts/')) file = join(fonts, path.slice(7))
    else if (path.startsWith('/assets/')) file = join(assets, path.slice(8))
    else if (path.startsWith('/shots/')) file = join(shots, path.slice(7))
    else if (path.startsWith('/src/')) file = join(sources, path.slice(5))
    else if (path.startsWith('/page/')) {
      response.writeHead(200, { 'Content-Type': 'text/html' })
      response.end(`<!doctype html><html><head><meta charset="utf-8"><style>${css}</style></head><body>${pages[path.slice(6)]}<script>${pageScript}</script></body></html>`)
      return
    } else throw new Error('not found')
    response.writeHead(200, { 'Content-Type': mime[extname(file).toLowerCase()] || 'application/octet-stream' })
    response.end(await readFile(file))
  } catch {
    response.writeHead(404); response.end()
  }
})
await new Promise(done => server.listen(0, '127.0.0.1', done))
const origin = `http://127.0.0.1:${server.address().port}`
const browser = await chromium.launch({ headless: true })
const written = []
try {
  const page = await browser.newPage({ viewport: { width: 1200, height: 600 }, deviceScaleFactor: 2 })
  const external = []
  await page.route('**/*', route => (new URL(route.request().url()).origin === origin ? route.continue() : (external.push(route.request().url()), route.abort())))
  for (const name of Object.keys(pages).filter(name => !only || only.has(name))) {
    await page.goto(`${origin}/page/${name}`)
    const missing = await page.evaluate(async () => {
      const faces = ['12px Mondwest', '16px Neuebit', '12px Mono']
      await Promise.all(faces.map(face => document.fonts.load(face)))
      return faces.filter(face => !document.fonts.check(face))
    })
    assert.deepEqual(missing, [], `${name}: fonts did not load`)
    await page.evaluate(async () => { await Promise.all([...document.images].map(image => image.decode())) })
    await page.evaluate(() => window.render())
    await page.screenshot({ path: join(output, name) })
    written.push(name)
  }
  assert.deepEqual(external, [], 'Art must not fetch external resources')
} finally {
  await browser.close()
  server.close()
}
console.log(JSON.stringify({ output, images: written, size: '2400x1200' }, null, 2))
